#! /bin/bash

path="/usr/local/bin""/usr/local/bin"

############################################################
# Help                                                     #
############################################################
Help()
{
    # Display Help
    $path/famous-quotes/main.py -h
}

############################################################
# Quote                                                    #
############################################################
ShowQuote()
{
    # Show a quote
    $path/famous-quotes/main.py -s
}

AddQuote()
{
    # Add a quote
    $path/famous-quotes/main.py -a
}

RemoveQuote()
{
    # Remove a quote
    $path/famous-quotes/main.py -r

}

############################################################
# Delete                                                   #
############################################################
DeleteFamousQuotes()
{
    # Delete the programme
    rm -fr $path/famous-quotes
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################


############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options
while getopts ":h :s :a :r :d " option; do
    case $option in
        h) # Display Help
            Help
            exit;;
        s) # Display a quote
            ShowQuote
            exit;;
        a) # Add a quote
            AddQuote
            exit;;
        r) # Remove a quote
            RemoveQuote
            exit;;
        d) # Delete the famous-quotes permanently
            DeleteFamousQuotes
            echo
            echo "The Famous Quotes programme is successfully removed from $path."
            rm $path/fq
            echo
            exit;;
    esac
done

